### ISSUE TITLE
apply same analysis to mouse data

### ISSUE THREAD

**Issue by anne-urai** [kiante-fernandez/2023_choicehistory_HSSM#17]

**Comment by anne-urai** [comment]
- get eids from elife paper initially, then use larger query with more mice (3 sessions before trained)
- Compute lapses from average mouse data: gamma+lambda

**Comment by anne-urai** [comment]
Now at https://github.com/kiante-fernandez/2023_choicehistory_HSSM/tree/get_ibl_data

**Comment by anne-urai** [comment]
### ToDo
- [ ] figure out negative / NaN RTs
- [ ] use `firstMove` vs `respTime`
- [ ] get 3 sessions per mouse to boost trial count
- [ ] some dataviz of individual RT distributions
- [ ] connect with Felicia @ Churchland lab UCLA
